### ISSUE TITLE
Remove Multiple Nodes / Edges

### ISSUE THREAD

**Issue by vin-ni** [Gencaster/gencaster#102]
Theoretically already implemented in the editor.

Right now it's blocked via the frontend. Need to check if it's causing any bugs to run the async calls in a loop.

**Comment by vin-ni** [comment]
This is actually a bug right now since it's possible to do exactly that.
We should order the deletion order by edge, then node.

**Comment by vin-ni** [comment]
I opened a [branch](https://github.com/Gencaster/gencaster/tree/102-remove-multiple-nodes-edges) to fix the multiple deletion error. Weirdly, i need a minimum of 100ms of delay after deleting edges before deleting nodes to prevent an error.
https://github.com/Gencaster/gencaster/blob/aa3d430ed894fd897d6dbe4a1476a0280f9b0b80/caster-editor/src/components/MenuTabEdit.vue#L47-L87

This is what happens when there is no delay:

https://github.com/Gencaster/gencaster/assets/9806572/b1b0f7b1-a06f-42f8-be3b-236982ca5916



Is this maybe related to the subscription @capital-G ? Or do you have any other idea what is causing this?

**Comment by capital-G** [comment]
I think I know why this happens

https://github.com/Gencaster/gencaster/blob/a2edff77c1550246d3af29ba506af2c44273dd68/caster-editor/src/components/MenuTabEdit.vue#L50-L59

It turns out that `async` and `forEach` are not really a good combination since every `forEach` callback is its own async function which will be executed but not be synchronized but all run in paralell, see https://stackoverflow.com/a/37576787 , which recommends uses a traditional for loop.

So this means that we have a race condition in the editor which creates a problem: as a deletion of a node implies the deletion of all its connected edges the now request of deletion of a non-existing edge will fail in the backend.
I just checked also the backend code but here we don't have a race condition since we await the deletion of the node before we send out the graphql subscription updates.

https://github.com/Gencaster/gencaster/blob/a2edff77c1550246d3af29ba506af2c44273dd68/caster-back/gencaster/schema.py#L327-L351

But I don't understand how the "Accesed invalid graph" thing comes up - what are the logs in the docker output in this case? I think there should be an exception there as well.

**Comment by capital-G** [comment]
Can't reproduce it anymore so I assume it is fixed? Please reopen if necessary :)
